<p align="center"><font size="6"><b>Notebook de Charles-Henri SAINT-MARS</b</font></p>

# **Algèbre linéaire**

In [3]:
# Importation des modules
from random import randint
from random import seed
from math import sqrt
import numpy as np
import tensorflow as tf
import torch

## Le scalaire

In [4]:
# En algèbre linéaire, l’objet mathématique le plus simple est le scalaire, qui est un nombre. Un vecteur est une liste de scalaires. Un tenseur est une matrice de vecteurs. Un tenseur d’ordre supérieur est une matrice de tenseurs, et ainsi de suite.

scalaire = 3 
scalaire

3

## Les Vecteurs

### Vecteurs aléatoires

In [5]:
# Créer un vecteur aléatoire
# randint(valeur_min, valeur_max) : Cette fonction de la bibliothèque random génère un nombre entier aléatoire entre valeur_min et valeur_max (inclus).

# for _ in range(dimension) : Cette boucle se répète dimension fois. Le caractère de soulignement _ est souvent utilisé en Python pour une variable qui n'est pas utilisée.

# [randint(valeur_min, valeur_max) for _ in range(dimension)] : Ceci est une liste en compréhension qui génère une nouvelle liste. Pour chaque itération de la boucle, elle génère un nouveau nombre aléatoire et l'ajoute à la liste.

def créer_vecteur_aléatoire(dimension, valeur_min=0, valeur_max=10):
  return [randint(valeur_min, valeur_max) for _ in range(dimension)]

créer_vecteur_aléatoire(3)

[8, 1, 1]

In [6]:
seed(10) # Pour obtenir des résultats reproductibles
randint(0, 10)

9

In [7]:
seed(92024)
vect_1 = créer_vecteur_aléatoire(2)
vect_2 = créer_vecteur_aléatoire(2)

In [8]:
vect_1

[6, 2]

In [9]:
vect_2

[9, 7]

<p color="red">Un vecteur est une matrice de 1xN. <br>
Il peut être de la forme vector = [ 1, 2, 3 ] (une seule ligne) ou vector = [ [1],[2],[3] ] (une seule colonne)</p>

### Normes des vecteurs

In [10]:
# Norme L1
# La norme L1 d'un vecteur est la somme des valeurs absolues de ses composantes.

<img src="Norme_vecteur_L1.jpg" />

In [11]:
# abs(a) : Cette fonction retourne la valeur absolue de a. La valeur absolue d'un nombre est sa valeur sans signe. Par exemple, abs(-3) est 3 et abs(3) est aussi 3.

# [abs(a) for a in vecteur] : Ceci est une liste en compréhension qui génère une nouvelle liste. Pour chaque élément a dans vecteur, elle calcule abs(a) et ajoute le résultat à la liste.

# sum([abs(a) for a in vecteur]) : Cette fonction calcule la somme de tous les éléments de la liste. En d'autres termes, elle ajoute toutes les valeurs absolues des éléments du vecteur.

def norme_L1(vecteur):
  return sum([abs(a) for a in vecteur])

In [12]:
norme_L1(vect_1)

8

In [13]:
# Vérification avec numpy
np.linalg.norm(vect_1, ord=1)

8.0

In [14]:
# Norme L2
# La norme L2 d'un vecteur est la racine carrée de la somme des carrés de ses composantes.

<img src="Norme_vecteur_L2.jpg" />

In [15]:
# a ** 2 : Cette expression élève a au carré. En d'autres termes, elle multiplie a par lui-même.

# [a ** 2 for a in vecteur] : Ceci est une liste en compréhension qui génère une nouvelle liste. Pour chaque élément a dans vecteur, elle calcule a ** 2 et ajoute le résultat à la liste.

# sum([a ** 2 for a in vecteur]) : Cette fonction calcule la somme de tous les éléments de la liste. En d'autres termes, elle fait la somme de tous les carrés des éléments du vecteur.

# sum([a ** 2 for a in vecteur]) ** 0.5 : Cette expression calcule la racine carrée de la somme. En Python, ** 0.5 est l'opération de racine carrée.

def norme_L2(vecteur):
  return sum([a ** 2 for a in vecteur]) ** 0.5

In [16]:
norme_L2(vect_1)

6.324555320336759

In [17]:
# Vérification avec numpy
np.linalg.norm(vect_1, ord=2)

6.324555320336759

### Distance euclidienne entre deux vecteurs

In [18]:

# La distance euclidienne entre deux vecteurs est la racine carrée de la somme des carrés des différences de leurs composantes homologues.

<img src="Distance_euclidienne_entre_2_vecteurs.jpg" />

In [19]:
# (b - a) ** 2 : Cette expression calcule le carré de la différence entre les éléments correspondants b et a des deux vecteurs.

# for (b, a) in zip(vecteur2, vecteur1) : Cette boucle parcourt les paires d'éléments correspondants dans vecteur2 et vecteur1. La fonction zip combine les deux vecteurs en une liste de paires.

# [(b - a) ** 2 for (b, a) in zip(vecteur2, vecteur1)] : Ceci est une liste en compréhension qui génère une nouvelle liste. Pour chaque paire (b, a), elle calcule (b - a) ** 2 et ajoute le résultat à la liste.

# sum([(b - a) ** 2 for (b, a) in zip(vecteur2, vecteur1)]) : Cette fonction calcule la somme de tous les éléments de la liste. En d'autres termes, elle ajoute tous les carrés des différences entre les éléments correspondants des deux vecteurs.

# sum([(b - a) ** 2 for (b, a) in zip(vecteur2, vecteur1)]) ** 0.5 : Cette expression calcule la racine carrée de la somme. En Python, ** 0.5 est l'opération de racine carrée.

def distance_L2(vecteur2, vecteur1):
  return sum([(b - a) ** 2 for (b, a) in zip(vecteur2, vecteur1)]) ** 0.5

In [20]:
distance_L2(vect_2, vect_1)

5.830951894845301

In [21]:
# Vérification avec numpy
np.linalg.norm(np.array(vect_2) - np.array(vect_1), ord=2)

5.830951894845301

### Produit de deux vecteurs appelé produit scalaire

In [22]:
# Cette ligne de code calcule le produit scalaire de deux vecteurs, `vecteur1` et `vecteur2`. Voici comment cela fonctionne :

# 1. `a * b` : Cette expression multiplie les éléments correspondants `a` et `b` des deux vecteurs.

# 2. `for (a, b) in zip(vecteur1, vecteur2)` : Cette boucle parcourt les paires d'éléments correspondants dans `vecteur1` et `vecteur2`. La fonction `zip` combine les deux vecteurs en une liste de paires.

# 3. `[a * b for (a, b) in zip(vecteur1, vecteur2)]` : Ceci est une liste en compréhension qui génère une nouvelle liste. Pour chaque paire `(a, b)`, elle calcule `a * b` et ajoute le résultat à la liste.

# 4. `sum([a * b for (a, b) in zip(vecteur1, vecteur2)])` : Cette fonction calcule la somme de tous les éléments de la liste. En d'autres termes, elle ajoute tous les produits des éléments correspondants des deux vecteurs.

# Le produit scalaire est une opération fondamentale en algèbre linéaire et a de nombreuses applications, notamment en géométrie, en physique et en machine learning

def produit_scalaire(vecteur1, vecteur2):
  assert len(vecteur1) == len(vecteur2), "Les vecteurs doivent avoir la même dimension"
  return sum([a * b for (a, b) in zip(vecteur1, vecteur2)])

In [23]:
produit_scalaire(vect_1, vect_2)

68

In [24]:
# Vérification avec numpy
np.dot(vect_1, vect_2)

68

## Les Matrices

### Dimensions de matrices

In [25]:
# Matrice carré 2x2
np.array([[1, 2], 
          [3, 4]])

array([[1, 2],
       [3, 4]])

In [26]:
# Matrice de 2x3
# Cette matrice comporte 2 lignes et 3 colonnes :
np.array([[1, 2, 3], 
          [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# Matrice carré d'orde 4 (4x4)
np.array([[1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [9, 10, 11, 12], 
          [13, 14, 15, 16]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
# Matrice diagonale
# Une matrice diagonale est une matrice carrée dont les éléments non diagonaux sont tous nuls.
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
# Matrice scalaire
# Une matrice scalaire est une matrice diagonale dont les éléments diagonaux sont tous égaux.
np.diag([3, 3, 3, 3])

array([[3, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [30]:
# Matrice identité
# La matrice identité est une matrice diagonale dont les éléments diagonaux sont tous égaux à 1.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# Matrice nulle
# Une matrice nulle est une matrice dont tous les éléments sont nuls.
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
# Matrices égales
# Deux matrices sont égales si elles ont la même dimension et si tous leurs éléments homologues sont égaux.
np.array([[1, 2], 
          [3, 4]]) == np.array([[1, 2], 
                                [3, 4]])


array([[ True,  True],
       [ True,  True]])

In [33]:
# L'opposé d'une matrice
# L'opposé d'une matrice est la matrice obtenue en changeant le signe de tous ses éléments.
np.array([[-2, 5, 3], 
          [-4, 7, 1]]) * -1

array([[ 2, -5, -3],
       [ 4, -7, -1]])

### Opérations sur les matrices

#### Addition de matrices

In [34]:
# Addition de matrices
# Pour additionner deux matrices, il faut que leurs dimensions soient identiques.
# L'addition de deux matrices se fait en additionnant leurs éléments homologues.
np.array([[1, 2], 
          [3, 4]]) + np.array([[5, 6], 
                               [7, 8]])

array([[ 6,  8],
       [10, 12]])

In [35]:
# Soustraction de matrices
# Pour soustraire deux matrices, il faut que leurs dimensions soient identiques.
# La soustraction de deux matrices se fait en soustrayant leurs éléments homologues.
np.array([[1, 2], 
          [3, 4]]) - np.array([[5, 6], 
                               [7, 8]])

array([[-4, -4],
       [-4, -4]])

In [36]:
# Multiplication d'une matrice par un scalaire
# Pour multiplier une matrice par un scalaire, il faut multiplier tous ses éléments par ce scalaire.
np.array([[1, 2], 
          [3, 4]]) * 2

array([[2, 4],
       [6, 8]])

In [37]:
# Dividion d'une matrice par un scalaire
# Pour diviser une matrice par un scalaire, il faut diviser tous ses éléments par ce scalaire.
np.array([[1, 2], 
          [3, 4]]) / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [38]:
# Transposée d'une matrice
# La transposée d'une matrice est la matrice obtenue en échangeant ses lignes et ses colonnes.
# Lorsque vous permutez des lignes et des colonnes, vous faites pivoter la matrice autour de sa diagonale.
# La diagonale va de la case en haut à gauche à la case en bas à droite (sens de l'antislah).
np.array([[1, 2], 
          [3, 4]]).T

array([[1, 3],
       [2, 4]])

In [39]:
# Produit matriciel
# Le produit de deux matrices A et B est une matrice C.
# Pour que le produit A.B soit possible, le nombre de colonnes de A doit être égal au nombre de lignes de B.
# La matrice C a autant de lignes que A et autant de colonnes que B.
# Chaque élément de C est le produit scalaire d'une ligne de A par une colonne de B.
mA = np.array([1, 2, 3])

mB = np.array([[1, 4, 7], 
              [2, 5, 8], 
              [3, 6, 9]])

mC = np.dot(mA, mB) # [1+4+9, 4+10+18, 7+16+27]
mC

array([14, 32, 50])

### Les Tenseurs

Un <b>tenseur</b>  est une <b>matrice à n dimensions</b>  :
 - Un scalaire est un tenseur de dimension 0
 - Un vecteur est un tenseur à 1 dimension
 - Une matrice est un tenseur à 2 dimensions <br>
Un <b>tenseur</b> est une généralisation de <b>vecteurs</b> et de <b>matrices</b> à des dimensions supérieures.

### Les grades tensoriels

Le nombre de directions qu’un tenseur peut avoir dans un espace à <b>N dimensions</b> est appelé le <b>rang du tenseur</b>.

Le rang est <b>noté R</b>.

Un <b>scalaire</b> est un nombre unique.
- Il a 0 axes
- Il a un <b>rang de 0</b>
- Il s’agit d’un tenseur de dimension 0

Un <b>vecteur</b> est un tableau à une dimension.
- Il a 1 axe
- Il a un <b>rang de 1</b> 
- Il s’agit d’un <b>tenseur à 1 dimension</b>

Une <b>matrice</b> est un tableau à 2 dimensions.
- Il a 2 axes
- Il a un <b>rang de 2</b> 
- Il s’agit d’un <b>tenseur à 2 dimensions</b>

Techniquement, tout ce qui précède sont des tenseurs, mais lorsque nous parlons de tenseurs, nous parlons de matrices de dimension supérieure à 2 (<b>R > 2</b>).

Pour créer et <b>manipuler des tenseurs en Python</b>, le module le plus couramment utilisé est <b>TensorFlow</b> ou <b>PyTorch</b>, qui sont des bibliothèques populaires pour le calcul numérique et l'apprentissage automatique (ou machine learning).

### Tensorflow

In [40]:
# Création d'un tenseur 2x2 avec des valeurs constantes
tensor = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)

print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [41]:
# Création de deux tenseurs
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Addition des deux tenseurs
result = tf.add(tensor1, tensor2)

print(result)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### PyTorch

In [42]:
# Créer deux tenseurs
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Additionner les deux tenseurs
result = tensor1 + tensor2

print(result)

tensor([5, 7, 9])


### Implémentation de produit de matrices (sans numpy)

In [43]:
# Créer une matrice aléatoire
def créer_matrice_aléatoire(lignes, colonnes, valeur_min=-5, valeur_max=5):
  matrix = []  
  for _ in range(lignes):
    ligne = []
    for _ in range(colonnes):
      nombre_aléatoire = randint(valeur_min, valeur_max)
      ligne.append(nombre_aléatoire)
    matrix.append(ligne)
  return matrix

In [44]:
mD = créer_matrice_aléatoire(3, 3)

mD # Matrice 3x4 à deux dimensions car il y a 2 crochets ouvrants avant la première cellule.

[[2, -4, 2], [-3, 1, 3], [4, -1, 4]]

In [45]:
mE = créer_matrice_aléatoire(3, 3)
mE # Matrice 3x4 à deux dimensions car il y a 2 crochets ouvrants avant la première cellule.

[[2, 4, -5], [4, 3, 4], [1, 2, -3]]

In [46]:
# Transposer la matrice mE

# zip(*mE) : La fonction zip combine plusieurs listes en une seule liste de tuples, où chaque tuple contient les éléments correspondants de chaque liste. L'opérateur * est utilisé pour déballer les listes de la matrice mE. En d'autres termes, zip(*mE) retourne une liste de tuples, où chaque tuple contient les éléments d'une colonne de la matrice mE.

# number for number in colonne_mE : Cette expression parcourt chaque nombre number dans un tuple colonne_mE retourné par zip(*mE).

# [number for number in colonne_mE] : Ceci est une liste en compréhension qui génère une nouvelle liste. Pour chaque nombre number dans colonne_mE, elle ajoute number à la liste.

# [[number for number in colonne_mE] for colonne_mE in zip(*mE)] : Ceci est une liste en compréhension imbriquée qui génère une nouvelle liste de listes. Pour chaque tuple colonne_mE retourné par zip(*mE), elle génère une nouvelle liste et ajoute cette liste à la liste globale.

# print([[number for number in colonne_mE] for colonne_mE in zip(*mE)]) : Cette fonction imprime la liste de listes générée par la liste en compréhension imbriquée.

print([[number for number in colonne_mE] for colonne_mE in zip(*mE)])

[[2, 4, 1], [4, 3, 2], [-5, 4, -3]]


In [47]:
len(mE), len(mE[0]) # len(EA) est le nombre de lignes et len(A[0]) est le nombre de colonnes

(3, 3)

In [48]:
# Créer une fonction shape pour retourner le nombre de lignes et de colonnes d'une matrice
def shape(matrice):
  return len(matrice), len(matrice[0])

In [49]:
shape(mD)

(3, 3)

In [50]:
# Créer une fonction pour multiplier deux matrices

# Pour chaque ligne1 dans matrice1, elle effectue les opérations suivantes :
# Pour chaque colonne2 dans la transposée de matrice2 (c'est ce que fait zip(*matrice2)), elle effectue les opérations suivantes :
# Elle multiplie chaque élément a de ligne1 par l'élément correspondant b dans colonne2 (c'est ce que fait a * b for a, b in zip(ligne1, colonne2)).
# Elle somme tous ces produits pour obtenir un seul nombre (c'est ce que fait sum([a * b for a, b in zip(ligne1, colonne2)])).
# Elle répète ces opérations pour chaque colonne2 dans la transposée de matrice2, ce qui donne une nouvelle ligne dans la matrice résultante.
# Elle répète ces opérations pour chaque ligne1 dans matrice1, ce qui donne la matrice résultante.

def produit_matriciel(matrice1, matrice2) -> list:
  shape_matrix1 = shape(matrice1)
  shape_matrix2 = shape(matrice2)
  print(f"shape de {matrice1} est {shape_matrix1}, shape de {matrice2} est {shape_matrix2}") # Afficher les dimensions des matrices
  assert shape_matrix1[1] == shape_matrix2[0], "Le nombre de colonnes de la première matrice doit être égal au nombre de lignes de la deuxième matrice"
  return [[sum([a * b for a, b in zip(ligne1, colonne2)]) for colonne2 in zip(*matrice2)] for ligne1 in matrice1]

In [51]:
produit_matriciel(mD, mE)

shape de [[2, -4, 2], [-3, 1, 3], [4, -1, 4]] est (3, 3), shape de [[2, 4, -5], [4, 3, 4], [1, 2, -3]] est (3, 3)


[[-10, 0, -32], [1, -3, 10], [8, 21, -36]]

In [52]:
# Vérification avec numpy
np.dot(mD, mE)

array([[-10,   0, -32],
       [  1,  -3,  10],
       [  8,  21, -36]])

In [53]:
# Vérification avec TensorFlow
tensor1 = tf.constant(mD)
tensor2 = tf.constant(mE)
result = tf.matmul(tensor1, tensor2)
print(result)

tf.Tensor(
[[-10   0 -32]
 [  1  -3  10]
 [  8  21 -36]], shape=(3, 3), dtype=int32)


In [54]:
# Vérification avec PyTorch
tensor1 = torch.tensor(mD)
tensor2 = torch.tensor(mE)
result = torch.mm(tensor1, tensor2)
print(result)

tensor([[-10,   0, -32],
        [  1,  -3,  10],
        [  8,  21, -36]])


### Implémentation de la matrice identité (sans numpy)

Une matrice identité est une matrice carrée qui a des 1s sur la diagonale principale et des 0s ailleurs. <br>
mA x mI = mA (où mI est la matrice identité)

In [55]:
# Créer une matrice identité

# for i in range(dimension): Pour chaque ligne i dans la matrice (de 0 à dimension - 1).
# for j in range(dimension): Pour chaque colonne j dans la matrice (de 0 à dimension - 1).
# 1 if i == j else 0: Si la ligne i est la même que la colonne j (c'est-à-dire que nous sommes sur la diagonale principale), alors mettez un 1. Sinon, mettez un 0.
# [[... for j in range(dimension)] for i in range(dimension)]: Ceci est une liste en compréhension imbriquée qui génère une liste de listes, ce qui est une représentation courante d'une matrice en Python.

def créer_matrice_identité(dimension):
  return [[1 if i == j else 0 for j in range(dimension)] for i in range(dimension)]

In [56]:
mI = créer_matrice_identité(5)
mI

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

### Implémentation d'une matrice inverse (sans numpy)

- Une matrice inverse est une matrice carrée qui donne l'identité lorsqu'elle est multipliée par l'original. <br>
- mA x mB = mI (où mB est la matrice inverse de mA et mI est la matrice identité) <br>
- Toutes les matrices n'ont pas forcément d'inverse. Une matrice qui a une inverse est appelée une matrice inversible ou non singulière.
- Certaines matrices non carrées ont des inverses appelées pseudo inverses. Par exemple, une matrice 2x3 a une inverse 3x2.

In [57]:
 # Créer une fonction pour inverser une matrice

# Ce bloc de code définit une fonction `matrice_inverse(matrice)` qui calcule l'inverse d'une matrice carrée en utilisant la méthode de Gauss-Jordan. Voici comment cela fonctionne :

# 1. `assert shape(matrice)[0] == shape(matrice)[1], "La matrice doit être carrée"` : Cette ligne vérifie que la matrice est carrée (c'est-à-dire qu'elle a le même nombre de lignes et de colonnes). Si ce n'est pas le cas, elle génère une erreur.

# 2. `dimension = shape(matrice)[0]` : Cette ligne détermine la dimension de la matrice (c'est-à-dire le nombre de lignes ou de colonnes).

# 3. `matrice_identité = créer_matrice_identité(dimension)` : Cette ligne crée une matrice identité de la même dimension que la matrice d'entrée.

# 4. `matrice_augmentée = [ligne1 + ligne2 for ligne1, ligne2 in zip(matrice, matrice_identité)]` : Cette ligne crée une matrice augmentée en combinant la matrice d'entrée et la matrice identité.

# 5. Les deux boucles `for` suivantes effectuent l'élimination de Gauss-Jordan sur la matrice augmentée. Cette méthode transforme la matrice en une forme réduite par lignes échelonnées, ce qui permet de trouver l'inverse de la matrice.

# 6. `return [ligne[dimension:] for ligne in matrice_augmentée]` : Cette ligne retourne la partie droite de la matrice augmentée, qui est l'inverse de la matrice d'entrée.

# En résumé, cette fonction prend une matrice carrée en entrée et retourne son inverse. Si la matrice n'est pas carrée, elle génère une erreur. Si la matrice n'est pas inversible (c'est-à-dire si son déterminant est zéro), la fonction peut générer une erreur de division par zéro.

def matrice_inverse(matrice):
  assert shape(matrice)[0] == shape(matrice)[1], "La matrice doit être carrée"
  dimension = shape(matrice)[0]
  matrice_identité = créer_matrice_identité(dimension)
  matrice_augmentée = [ligne1 + ligne2 for ligne1, ligne2 in zip(matrice, matrice_identité)]
  for i in range(dimension):
    pivot = matrice_augmentée[i][i]
    matrice_augmentée[i] = [a / pivot for a in matrice_augmentée[i]]
    for j in range(dimension):
      if i != j:
        coefficient = matrice_augmentée[j][i]
        matrice_augmentée[j] = [a - coefficient * b for a, b in zip(matrice_augmentée[j], matrice_augmentée[i])]
  return [ligne[dimension:] for ligne in matrice_augmentée]

In [58]:
mF = [[4, -2, 3], [8, -3, 5], [7, -2, 4]]
mF_inv = matrice_inverse(mF)
mF_inv

[[-2.0, 2.0, -1.0], [3.0, -5.0, 4.0], [5.0, -6.0, 4.0]]

In [59]:
# Vérification avec numpy
np.linalg.inv(np.array(mF))

array([[-2.,  2., -1.],
       [ 3., -5.,  4.],
       [ 5., -6.,  4.]])

### Implémentation de la transposée d'une matrice (sans numpy)

- La transposée d'une matrice est la matrice obtenue en échangeant ses lignes et ses colonnes. <br>
- Lorsque vous permutez des lignes et des colonnes, vous faites pivoter la matrice autour de sa diagonale. <br>
- La diagonale va de la case en haut à gauche à la case en bas à droite (sens de l'antislah).


In [60]:
# Déterminer la transposée d'une matrice

# for i in range(len(matrice[0])) : Pour chaque colonne i dans la matrice originale (de 0 à len(matrice[0]) - 1).
# for j in range(len(matrice)) : Pour chaque ligne j dans la matrice originale (de 0 à len(matrice) - 1).
# matrice[j][i] : Prenez l'élément à la ligne j et à la colonne i de la matrice originale.
# [matrice[j][i] for j in range(len(matrice))] : Créez une nouvelle ligne qui contient les éléments de la colonne i de la matrice originale.
# [[... for i in range(len(matrice[0]))] : Faites cela pour chaque colonne i dans la matrice originale, ce qui donne la matrice transposée.

def transposer(matrice):
    return [[matrice[j][i] for j in range(len(matrice))] for i in range(len(matrice[0]))]

In [61]:
mG = créer_matrice_aléatoire(5, 5)
mG
                             

[[5, -4, 2, 2, 2],
 [-4, 4, 3, 0, -5],
 [5, -2, 3, 2, -5],
 [2, -3, -5, -4, 2],
 [-2, -3, 1, 5, -4]]

In [62]:
transposer(mG)

[[5, -4, 5, 2, -2],
 [-4, 4, -2, -3, -3],
 [2, 3, 3, -5, 1],
 [2, 0, 2, -4, 5],
 [2, -5, -5, 2, -4]]

In [63]:
transposer(mI) # La transposée d'une matrice identité est elle-même

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]